keys:
  - &desktop_alex age1qaxfw7w2ylzyapqgkvydw8jntq54mvv2eqspazerfkme6pquadvszg2dqm
  - &spicems age1uq3yl9cjmvgxhcp4m9as4g75p9p0lfunqpn0lrywsnkucw40c4qql6dgp6
creation_rules:
  # Desktop Secrets
  - path_regex: hosts/desktop/system/security/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *desktop_alex
        #    - *nixos
  - path_regex: hosts/.*/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *desktop_alex
        - *spicems
