{
  pkgs,
  lib,
  config,
  ...
}: let
  vars = import ./variables.nix;
in {
  # Main Dozzle UI
  virtualisation.oci-containers.containers."dozzle" = {
    autoStart = true;
    #user = "alex:users";

    image = "amir20/dozzle:latest";
    volumes = [
      "/home/alex/docker/dozzle/fake-engine-id:/var/lib/docker/engine-id:ro" # Podman compatibility
      #"/var/run/user/1000/podman/podman.sock:/var/run/docker.sock" # Points dozzle to user docker.socket
      "/run/podman/podman.sock:/var/run/docker.sock"
    ];
    ports = ["9999:8080/tcp"];
    #environment = {
    #  DOZZLE_DOCKER_HOST = "unix:///var/run/docker.sock";
    #};
    #networks = ["t2_proxy"];
    log-driver = vars.common.logDriver;
    extraOptions = [
      "--network-alias=dozzle"
      #  "--network=t2_proxy"
    ];

    #   labels = {
    #     "traefik.enable" = "true";
    #     "traefik.http.routers.dozzle-rtr.entrypoints" = "https";
    #     "traefik.http.routers.dozzle-rtr.middlewares" = "chain-authelia@file";
    #     "traefik.http.routers.dozzle-rtr.rule" = "Host(`logs.spice.cx`)";
    #     "traefik.http.routers.dozzle-rtr.service" = "dozzle-svc";
    #     "traefik.http.routers.dozzle-rtr.tls" = "true";
    #     "traefik.http.services.dozzle-svc.loadbalancer.server.port" = "8080";
    #   };
  };

  systemd.services."podman-dozzle" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    wants = ["podman.service"];
    after = ["podman.service"];
    partOf = ["podman-compose-dozzle-root.target"];
    wantedBy = ["podman-compose-dozzle-root.target"];
  };

  # Root target
  systemd.targets."podman-compose-dozzle-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };

  # Network creation
  # systemd.services.create-podman-t2-proxy-network = {
  #   description = "Create Podman t2_proxy network";
  #   wantedBy = ["multi-user.target"];
  #   before = ["podman-dozzle.service"];
  #   script = ''
  #     ${pkgs.podman}/bin/podman network exists t2_proxy || ${pkgs.podman}/bin/podman network create t2_proxy
  #   '';
  # };
}
